be6 Create base code for Movie hive back end #6
dasamantaraoaditya/watchhivebe pull request #3
Opened 2022-03-13 18:12 UTC by ganesankarthikeyan

Created skeleton for our watchhivebe.
Most of them are autogenerated.
Main things to notice
    Main class
    Pom.xml
    Readme
    Basic look at the structure.

2022-03-13 19:09 UTC, daredevilteja commented on README.md
> +1) Make sure you have JDK 8 or 11. (JDK 8 is preffered)
change the spelling of preferred

2022-03-13 19:11 UTC, daredevilteja requested changes
When I am starting the project then I am getting an error
Whitelabel Error page - is this an expected error

2022-03-13 19:11 UTC, daredevilteja commented on README.md
> +1) Make sure you have JDK 8 or 11. (JDK 8 is preffered)
Change the spelling of preferred

2022-03-13 19:49 UTC, dasamantaraoaditya commented
> When I am starting the project then I am getting an error Whitelabel Error page - is this an expected error

Yes , i think that is expected as we dont have any api yet and it falls to default error page.
Except for the review comments above, everything else looks good to me.

2022-03-14 06:42 UTC, ganesankarthikeyan commented on README.md
> +1) Make sure you have JDK 8 or 11. (JDK 8 is preffered)
resolved.

2022-03-14 07:48 UTC, merged